// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaApi.Service;

namespace TriviaApi.Migrations
{
    [DbContext(typeof(Dbcontext))]
    [Migration("20200909160224_firstdata")]
    partial class firstdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriviaApi.Entities.Trivia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Questions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trivias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95a"),
                            Answers = "Brown",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "What is the rarest M&M color?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95b"),
                            Answers = "World Wide Web",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "In a website browser address bar, what does “www” stand for?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95c"),
                            Answers = "1987",
                            Category = 2,
                            Difficulty = 0,
                            Questions = "In what year were the first Air Jordan sneakers released?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95d"),
                            Answers = "21",
                            Category = 6,
                            Difficulty = 0,
                            Questions = " In a game of bingo, which number is represented by the phrase \"two little duck\"?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95e"),
                            Answers = "Pandora",
                            Category = 2,
                            Difficulty = 1,
                            Questions = "According to Greek mythology who was the first woman on earth?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b95f"),
                            Answers = "They won the popular vote, but lost the electoral-college vote",
                            Category = 2,
                            Difficulty = 0,
                            Questions = "Samuel Tilden, Grover Cleveland, Al Gore and Hillary Clinton share what distinction among U.S. presidential candidates?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b99c"),
                            Answers = "Ethopia",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Which African country was formerly known as Abyssinia?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96a"),
                            Answers = "The Australian Open",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Tennis star Serena Williams won which major tournament while pregnant with her first child?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96b"),
                            Answers = "Paris",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "In which European city would you find Orly airport?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96c"),
                            Answers = "Lady Gaga",
                            Category = 4,
                            Difficulty = 0,
                            Questions = "Which singer’s real name is Stefani Joanne Angelina Germanotta?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96d"),
                            Answers = "The Platypus",
                            Category = 3,
                            Difficulty = 0,
                            Questions = "The only known monotremes in the animal kingdom are the echidna and which other creature?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96e"),
                            Answers = "Gwen Stafani",
                            Category = 4,
                            Difficulty = 0,
                            Questions = "Kingston, Zuma, and Apollo are the sons of which American female pop star ?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b96f"),
                            Answers = "Dakota Building",
                            Category = 2,
                            Difficulty = 0,
                            Questions = "Outside which New York building was John Lennon killed?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b99a"),
                            Answers = "Great Dane",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "What is the tallest breed of dog in the world?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97a"),
                            Answers = "Hamlet",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Which of Shakespeare’s plays is the longest?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97b"),
                            Answers = "Boxing Day",
                            Category = 4,
                            Difficulty = 0,
                            Questions = "In the United Kingdom, what is the day after Christmas known as?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97c"),
                            Answers = "Aglet",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "What is the tiny piece at the end of a shoelace called?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97d"),
                            Answers = "Mr.Potato Head",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "What was the first toy to be advertised on television?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97e"),
                            Answers = "Sperm Whale",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "What is the loudest animal on Earth?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b97f"),
                            Answers = "Arizona and Hawaii",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Which two U.S. states don’t observe Daylight Saving Time?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b99b"),
                            Answers = "Switzerland",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Which country consumes the most chocolate per capita?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b98a"),
                            Answers = "Forx Knox",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Where were the Declaration of Independence, the Constitution, and the Bill of Rights stored during World War II?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b98b"),
                            Answers = "Vermeer",
                            Category = 6,
                            Difficulty = 0,
                            Questions = "Which Dutch artist painted “Girl with a Pearl Earring”?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b98c"),
                            Answers = "A.A.Milne",
                            Category = 0,
                            Difficulty = 0,
                            Questions = "Which author wrote the ‘Winnie-the-Pooh’ books?"
                        },
                        new
                        {
                            Id = new Guid("3222152b-c0f9-472d-be10-e8aff0f4b98d"),
                            Answers = "Volcanos",
                            Category = 3,
                            Difficulty = 0,
                            Questions = "Fissures, vents and plugs are all associated with which geological feature?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
